##### Semi-supervised Training ######
Train: 
  model_name: 'MODEL_NAME'			## model names to save log file or wandb.
  log_path: './log'				## path to the log file, only works when the wandb option is False.
  use_cuda: True
  seed: 41
  start_epoch: 0
  end_epoch: 200
  batch_size: 8
  num_workers: 8 
  lr: 1e-4
  d_consistency : 1.0				## depth consistency loss weight
  f_consistency : 1.0				## feature consistency loss weight		
  K : 64						## set number of K for K-way masking, 64 is the default
  wandb : False
  load_optim : False
  
  model:
    baseline: "DPT" # ["DPT", "monodepth2"]
    max_depth: 10.0 # use 10 for NYU and 80 for KITTI depth
    load_weight : False
    weight_path : './weight'
    mlp_head: True					## prediction head for feature consistency loss
  add_model:
    uncert: True					## use uncertainty network. if True, consistency loss is weighted by uncertainty
    load_weight : False
    weight_path : './weight'
    threshold: 0.7

  label_data:
    height: 480
    width: 640
    dataset: 'nyu'
    splits: 'nyu'
    data_path: 'DATA_PATH'
    img_ext: '.jpg'

  unlabeled_data:
    height: 480
    width: 640
    dataset: 'nyu'
    splits: 'nyu'
    data_path: 'DATA_PATH'
    img_ext: '.jpg'

