##### Semi-supervised Training ######
Train: 
  model_name: 'MODEL_NAME'
  log_path: './log'
  use_cuda: True
  seed: 41
  start_epoch: 0
  end_epoch: 200
  batch_size: 8
  num_workers: 8 
  lr: 1e-4
  d_consistency : 1.0
  f_consistency : 1.0
  w_patch : 0.0
  K : 64
  wandb : True
  load_optim : False
  
  model:
    baseline: "DPT" # ["DPT", "monodepth2"]
    max_depth: 80.0 # use 10 for NYU and 80 for KITTI depth
    load_weight : False
    weight_path : './weight'
    mlp_head: True
  add_model:
    uncert: True
    ccnn: False
    load_weight : False
    weight_path : './weight'
    threshold: 0.7

  label_data:
    height: 192
    width: 640
    dataset: 'kitti_depth'
    splits: 'eigen_temp'
    data_path: 'DATA_PATH'
    img_ext: '.jpg'

  unlabeled_data:
    height: 192
    width: 640
    dataset: 'kitti_depth'
    splits: 'eigen_temp'
    data_path: 'DATA_PATH'
    img_ext: '.jpg'

